### ISSUE TITLE
Export and import of questions without QTI

### ISSUE THREAD

**Issue by rschlaefli** [uzh-bf/klicker-uzh-legacy#5]
- A batch of questions can be exported from the question pool by clicking a button
- The exported questions are saved to a JSON file
- The exported questions contain data related to the latest version of the question. No user-related data is included such that the exports can be shared.
- An upload dialog enables upload of the JSON file and shows an overview of all questions to be uploaded

**Comment by chilbes** [comment]
Tested the feature and works as expected. Nice and very useful!

In addition to the behavior specified above, tags are also exported and created upon import if they do not yet exist.

It would be nice to have a "select/unselect all" feature to make it easier to export a large set of questions. This would support the following "export all questions with specific tags" use-case

- select tags
- click "select all" to mark all questions
- export

Otherwise you need to scroll down and manually select each single question that should be exported.

Might be related to #41
